# Generated by Django 5.1.7 on 2025-03-28 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api_notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('linkedNotes', models.ManyToManyField(related_name='themes', to='api_notes.note')),
            ],
        ),
        migrations.CreateModel(
            name='AIAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteSimilarity', models.JSONField(default=dict)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='api_notes.note')),
                ('identified_theme', models.ManyToManyField(to='api_themes.theme')),
            ],
        ),
    ]
